#
# Created this compose only for My Projects
# May not work for other applications
# Use at your own risk
# - Rakib
#
version: '3.1'

services:
  db:
    image: mysql:5.7.40
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - project

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - project
networks:
  project:
    driver: bridge
